spring:
  application:
    name: spring-boot-admin-sample-eureka
  profiles:
    active:
      - insecure


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.251.195.186:3306/ifp_risk?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: smartlife
    password: belink!@#
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect


# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
#spring:
#  profiles: secure
#  security:
#    user:
#      name: "user"
#      password: "password"
#eureka:
#  instance:
#    metadata-map:
#      user.name: "user"         #These two are needed so that the server
#      user.password: "password" #can access the protected client endpoints

---
spring:
  boot:
    admin:
      deploy:
        jenkins:
          host: http://ifp3-dev1:8080/
          user: admin
          password: 111f8d28f9be0415cda322bc26cf5f78b5
        services:
          -
            name: user-front
            jenkinsJobName: ifp-poc
            projectName: app-user-front
            server:
              - ifp3-dev1
              - ifp3-dev2
          -
            name: user-center
            jenkinsJobName: ifp-poc
            projectName: app-user-center
            server:
              - ifp3-dev1
              - ifp3-dev2
